### ISSUE TITLE
NullpointerException on packages which only have interfaces.

### ISSUE THREAD

**Issue by ukinimod** [rodhilton/jasome#1]
I was analyzing one single java file with jasome-0.6.8-alpha which declared an interface and I got the following stacktrace:

Exception in thread "main" java.lang.NullPointerException
	at org.jasome.metrics.value.NumericValueSummaryStatistics.getAverage(NumericValueSummaryStatistics.java:25)
	at org.jasome.metrics.calculators.PackageAggregatorCalculator.calculate(PackageAggregatorCalculator.java:33)
	at org.jasome.metrics.calculators.PackageAggregatorCalculator.calculate(PackageAggregatorCalculator.java:16)
	at org.jasome.input.Processor.lambda$null$4(Processor.java:64)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1604)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:747)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:395)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:725)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:430)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:594)
	at org.jasome.input.Processor.lambda$process$5(Processor.java:63)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1604)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:747)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:395)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:725)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:430)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:594)
	at org.jasome.input.Processor.process(Processor.java:45)
	at org.jasome.executive.CommandLineExecutive.main(CommandLineExecutive.java:72)

and the programm crashed completely.

**Comment by rodhilton** [comment]
Thanks for bringing this to my attention, I'll take a look at it.  Would you mind posting the single Java file with an interface? I'm curious (just based on the stacktrace) if it was a default package file or not.

**Comment by ukinimod** [comment]
I made a fix in my fork with some other suggestions. I'll make a PR with them. Sorry that I didn't split these, I'm quite in a hurry fixing these issues. 

File is attached.
[SomeClass.txt](https://github.com/rodhilton/jasome/files/2473979/SomeClass.txt)
