### ISSUE TITLE
problem in execution (s.o. Windows)

### ISSUE THREAD

**Issue by fmininno** [rodhilton/jasome#10]
Exception in thread "main" java.lang.IllegalArgumentException: character to be escaped is missing
       at java.util.regex.Matcher.appendReplacement(Unknown Source)
       at java.util.regex.Matcher.replaceAll(Unknown Source)
       at java.lang.String.replaceAll(Unknown Source)
       at org.jasome.input.Scanner.configureParserAndResolver(Scanner.java:100)
       at org.jasome.input.Scanner.doScan(Scanner.java:25)
       at org.jasome.input.FileScanner.scan(FileScanner.java:47)
       at org.jasome.executive.CommandLineExecutive.main(CommandLineExecutive.java:70)

**Comment by rodhilton** [comment]
Windows is currently unsupported as I don't have a windows environment where I can fix and test whatever issue people are having in Windows.
